name              'djbdns'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs djbdns and configures DNS services'
version           '5.1.19'
source_url        'https://github.com/sous-chefs/djbdns'
issues_url        'https://github.com/sous-chefs/djbdns/issues'
chef_version      '>= 15.3'

supports 'almalinux', '= 9.0'
supports 'centos_stream', '= 9.0'
supports 'debian', '= 12.0'
supports 'ubuntu', '>= 22.04'
